# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountableUSDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CountableUSDemo
  # Pods for SegmentNativeClientLibsTest
  pod 'Analytics', '~> 3.0'
  pod 'Segment-Firebase'

  target 'CountableUSDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
